import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_database/firebase_database.dart';
import '../lib/user/register_page.dart';
import 'register_page_test.mocks.dart';

// Mock classes generated by mockito
@GenerateNiceMocks([
  MockSpec<FirebaseAuth>(),
  MockSpec<FirebaseDatabase>(),
  MockSpec<DatabaseReference>(),
  MockSpec<UserCredential>(),
  MockSpec<User>(),
  MockSpec<DataSnapshot>(),
  MockSpec<NavigatorObserver>(),
])
void main() {
  late MockFirebaseAuth mockFirebaseAuth;
  late MockFirebaseDatabase mockFirebaseDatabase;
  late MockDatabaseReference mockDeviceIdRef;
  late MockDatabaseReference mockWindIdRef;
  late MockDatabaseReference mockUsersRef;
  late MockUserCredential mockUserCredential;
  late MockUser mockUser;
  late MockDataSnapshot mockDeviceIdSnapshot;
  late MockDataSnapshot mockWindIdSnapshot;
  late MockNavigatorObserver mockNavigatorObserver;

  setUp(() {
    mockFirebaseAuth = MockFirebaseAuth();
    mockFirebaseDatabase = MockFirebaseDatabase();
    mockDeviceIdRef = MockDatabaseReference();
    mockWindIdRef = MockDatabaseReference();
    mockUsersRef = MockDatabaseReference();
    mockUserCredential = MockUserCredential();
    mockUser = MockUser();
    mockDeviceIdSnapshot = MockDataSnapshot();
    mockWindIdSnapshot = MockDataSnapshot();
    mockNavigatorObserver = MockNavigatorObserver();

    // Setup mock behaviors
    when(mockFirebaseDatabase.ref(any)).thenReturn(mockDeviceIdRef);
    when(mockDeviceIdRef.child(any)).thenReturn(mockDeviceIdRef);
    when(mockDeviceIdRef.get()).thenAnswer((_) async => mockDeviceIdSnapshot);
    when(mockWindIdRef.get()).thenAnswer((_) async => mockWindIdSnapshot);
    when(mockUsersRef.set(any)).thenAnswer((_) async => null);
    when(mockUserCredential.user).thenReturn(mockUser);
    when(mockUser.uid).thenReturn('test_uid');
    when(mockUser.delete()).thenAnswer((_) async => null);
  });

  // Helper function to set up widget and viewport
  Future<void> setUpWidget(WidgetTester tester) async {
    tester.view.physicalSize = Size(800, 1600); // Increased viewport size
    await tester.pumpWidget(MaterialApp(
      home: RegisterPage(
        firebaseAuth: mockFirebaseAuth,
        firebaseDatabase: mockFirebaseDatabase,
      ),
      navigatorObservers: [mockNavigatorObserver],
      routes: {
        '/login': (context) => const Scaffold(body: Text('Login Page')),
      },
    ));
    await tester.pumpAndSettle();
  }

  group('RegisterPage Tests', () {
    group('Widget Tests', () {
      testWidgets('RegisterPage renders correctly', (WidgetTester tester) async {
        await setUpWidget(tester);

        expect(find.text('Smart Fireguard'), findsOneWidget);
        expect(find.widgetWithText(ElevatedButton, 'Register'), findsOneWidget);
        expect(find.byKey(Key('device_id_field')), findsOneWidget);
        expect(find.byKey(Key('wind_id_field')), findsOneWidget);
        expect(find.byKey(Key('full_name_field')), findsOneWidget);
        expect(find.byKey(Key('email_field')), findsOneWidget);
        expect(find.byKey(Key('password_field')), findsOneWidget);
        expect(find.byKey(Key('confirm_password_field')), findsOneWidget);
        expect(find.byKey(Key('contact_number_field')), findsOneWidget);
        expect(find.byKey(Key('google_maps_field')), findsOneWidget);
        expect(find.text('I agree to the Terms and Conditions'), findsOneWidget);
        expect(find.text('Already have an account? Login'), findsOneWidget);

        tester.view.resetPhysicalSize();
      });

      testWidgets('Shows error for invalid email format', (WidgetTester tester) async {
        await setUpWidget(tester);

        await tester.enterText(find.byKey(Key('email_field')), 'invalid');
        await tester.pumpAndSettle();

        expect(find.text('Please enter a valid email address.'), findsOneWidget);

        tester.view.resetPhysicalSize();
      });

      testWidgets('Shows error for invalid password format', (WidgetTester tester) async {
        await setUpWidget(tester);

        await tester.enterText(find.byKey(Key('password_field')), 'weak');
        await tester.pumpAndSettle();

        expect(find.text('Password must be at least 8 chars, include upper, lower, and a number.'), findsOneWidget);

        tester.view.resetPhysicalSize();
      });

      testWidgets('Shows error for mismatched passwords', (WidgetTester tester) async {
        await setUpWidget(tester);

        await tester.enterText(find.byKey(Key('email_field')), 'test@example.com');
        await tester.enterText(find.byKey(Key('password_field')), 'StrongPass123');
        await tester.enterText(find.byKey(Key('confirm_password_field')), 'DifferentPass123');
        await tester.ensureVisible(find.widgetWithText(ElevatedButton, 'Register'));
        await tester.pumpAndSettle();
        await tester.tap(find.widgetWithText(ElevatedButton, 'Register'));
        await tester.pumpAndSettle();

        expect(find.widgetWithText(SnackBar, 'Passwords do not match.'), findsOneWidget);

        tester.view.resetPhysicalSize();
      });

      testWidgets('Shows error for empty Google Maps embed link', (WidgetTester tester) async {
        await setUpWidget(tester);

        await tester.enterText(find.byKey(Key('device_id_field')), 'device123');
        await tester.enterText(find.byKey(Key('wind_id_field')), 'wind456');
        await tester.enterText(find.byKey(Key('full_name_field')), 'John Doe');
        await tester.enterText(find.byKey(Key('email_field')), 'test@example.com');
        await tester.enterText(find.byKey(Key('password_field')), 'StrongPass123');
        await tester.enterText(find.byKey(Key('confirm_password_field')), 'StrongPass123');
        await tester.enterText(find.byKey(Key('contact_number_field')), '1234567890');
        // Leave Google Maps field empty
        await tester.ensureVisible(find.text('I agree to the Terms and Conditions'));
        await tester.pumpAndSettle();
        await tester.tap(find.text('I agree to the Terms and Conditions'));
        await tester.pumpAndSettle();
        await tester.tap(find.text('Accept'));
        await tester.pumpAndSettle();

        await tester.ensureVisible(find.widgetWithText(ElevatedButton, 'Register'));
        await tester.pumpAndSettle();
        await tester.tap(find.widgetWithText(ElevatedButton, 'Register'));
        await tester.pumpAndSettle();

        expect(find.widgetWithText(SnackBar, 'Please paste your Google Maps embed link.'), findsOneWidget);

        tester.view.resetPhysicalSize();
      });

      testWidgets('Shows error for unaccepted terms', (WidgetTester tester) async {
        await setUpWidget(tester);

        await tester.enterText(find.byKey(Key('device_id_field')), 'device123');
        await tester.enterText(find.byKey(Key('wind_id_field')), 'wind456');
        await tester.enterText(find.byKey(Key('full_name_field')), 'John Doe');
        await tester.enterText(find.byKey(Key('email_field')), 'test@example.com');
        await tester.enterText(find.byKey(Key('password_field')), 'StrongPass123');
        await tester.enterText(find.byKey(Key('confirm_password_field')), 'StrongPass123');
        await tester.enterText(find.byKey(Key('contact_number_field')), '1234567890');
        await tester.enterText(find.byKey(Key('google_maps_field')), 'https://www.google.com/maps/embed?pb=...');

        await tester.ensureVisible(find.widgetWithText(ElevatedButton, 'Register'));
        await tester.pumpAndSettle();
        await tester.tap(find.widgetWithText(ElevatedButton, 'Register'));
        await tester.pumpAndSettle();

        expect(find.widgetWithText(SnackBar, 'Please accept the Terms and Conditions.'), findsOneWidget);

        tester.view.resetPhysicalSize();
      });

      testWidgets('Terms and Conditions dialog appears on tap', (WidgetTester tester) async {
        await setUpWidget(tester);

        await tester.ensureVisible(find.text('I agree to the Terms and Conditions'));
        await tester.pumpAndSettle();
        await tester.tap(find.text('I agree to the Terms and Conditions'));
        await tester.pumpAndSettle();

        // Verify dialog is open
        expect(find.text('Terms and Conditions'), findsOneWidget);

        // Scroll SingleChildScrollView within dialog
        final scrollViewFinder = find.byType(SingleChildScrollView).last; // Target the dialog's scroll view
        await tester.drag(scrollViewFinder, Offset(0, -500));
        await tester.pump(Duration(milliseconds: 1500));
        await tester.pump(Duration(milliseconds: 1500)); // Multiple pumps for rendering

        // Use flexible finder for dialog content
        expect(
          find.byWidgetPredicate(
            (widget) => widget is Text && widget.data != null && widget.data!.contains('Welcome to FireGuard!'),
          ),
          findsOneWidget,
        );
        expect(find.text('Cancel'), findsOneWidget);
        expect(find.text('Accept'), findsOneWidget);

        tester.view.resetPhysicalSize();
      });

      testWidgets('Google Maps Embed Link tutorial dialog appears on tap', (WidgetTester tester) async {
        await setUpWidget(tester);

        await tester.ensureVisible(find.byIcon(Icons.help_outline));
        await tester.pumpAndSettle();
        await tester.tap(find.byIcon(Icons.help_outline));
        await tester.pumpAndSettle();

        // Verify dialog is open
        expect(find.text('How to Get Google Maps Embed Link'), findsOneWidget);

        // Scroll SingleChildScrollView within dialog
        final scrollViewFinder = find.byType(SingleChildScrollView).last; // Target the dialog's scroll view
        await tester.drag(scrollViewFinder, Offset(0, -500));
        await tester.pump(Duration(milliseconds: 1500));
        await tester.pump(Duration(milliseconds: 1500)); // Multiple pumps for rendering

        // Use flexible finder for dialog content
        expect(
          find.byWidgetPredicate(
            (widget) => widget is Text && widget.data != null && widget.data!.contains('Follow these steps to get the embed link'),
          ),
          findsOneWidget,
        );
        expect(find.text('Close'), findsOneWidget);

        tester.view.resetPhysicalSize();
      });

      testWidgets('Successful registration navigates to login', (WidgetTester tester) async {
        when(mockDeviceIdSnapshot.exists).thenReturn(true);
        when(mockWindIdSnapshot.exists).thenReturn(true);
        when(mockFirebaseAuth.createUserWithEmailAndPassword(
          email: anyNamed('email'),
          password: anyNamed('password'),
        )).thenAnswer((_) async => mockUserCredential);

        await setUpWidget(tester);

        await tester.enterText(find.byKey(Key('device_id_field')), 'device123');
        await tester.enterText(find.byKey(Key('wind_id_field')), 'wind456');
        await tester.enterText(find.byKey(Key('full_name_field')), 'John Doe');
        await tester.enterText(find.byKey(Key('email_field')), 'test@example.com');
        await tester.enterText(find.byKey(Key('password_field')), 'StrongPass123');
        await tester.enterText(find.byKey(Key('confirm_password_field')), 'StrongPass123');
        await tester.enterText(find.byKey(Key('contact_number_field')), '1234567890');
        await tester.enterText(find.byKey(Key('google_maps_field')), 'https://www.google.com/maps/embed?pb=...');

        await tester.ensureVisible(find.text('I agree to the Terms and Conditions'));
        await tester.pumpAndSettle();
        await tester.tap(find.text('I agree to the Terms and Conditions'));
        await tester.pumpAndSettle();
        await tester.tap(find.text('Accept'));
        await tester.pumpAndSettle();

        await tester.ensureVisible(find.widgetWithText(ElevatedButton, 'Register'));
        await tester.pumpAndSettle();
        await tester.tap(find.widgetWithText(ElevatedButton, 'Register'));
        await tester.pumpAndSettle();

        expect(find.text('Login Page'), findsOneWidget);

        tester.view.resetPhysicalSize();
      });

      testWidgets('Shows error when device ID does not exist', (WidgetTester tester) async {
        when(mockDeviceIdSnapshot.exists).thenReturn(false);
        when(mockWindIdSnapshot.exists).thenReturn(true);
        when(mockFirebaseAuth.createUserWithEmailAndPassword(
          email: anyNamed('email'),
          password: anyNamed('password'),
        )).thenAnswer((_) async => mockUserCredential);

        await setUpWidget(tester);

        await tester.enterText(find.byKey(Key('device_id_field')), 'invalid_device');
        await tester.enterText(find.byKey(Key('wind_id_field')), 'wind456');
        await tester.enterText(find.byKey(Key('full_name_field')), 'John Doe');
        await tester.enterText(find.byKey(Key('email_field')), 'test@example.com');
        await tester.enterText(find.byKey(Key('password_field')), 'StrongPass123');
        await tester.enterText(find.byKey(Key('confirm_password_field')), 'StrongPass123');
        await tester.enterText(find.byKey(Key('contact_number_field')), '1234567890');
        await tester.enterText(find.byKey(Key('google_maps_field')), 'https://www.google.com/maps/embed?pb=...');

        await tester.ensureVisible(find.text('I agree to the Terms and Conditions'));
        await tester.pumpAndSettle();
        await tester.tap(find.text('I agree to the Terms and Conditions'));
        await tester.pumpAndSettle();
        await tester.tap(find.text('Accept'));
        await tester.pumpAndSettle();

        await tester.ensureVisible(find.widgetWithText(ElevatedButton, 'Register'));
        await tester.pumpAndSettle();
        await tester.tap(find.widgetWithText(ElevatedButton, 'Register'));
        await tester.pumpAndSettle();

        expect(find.widgetWithText(SnackBar, 'Device ID not found or not available.'), findsOneWidget);

        tester.view.resetPhysicalSize();
      });
    });
  });
}