// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx3ARkEsL85ibdj7e9PsgNNAtB5BtDBHI',
    appId: '1:43511634572:web:5af581e4c22a3925e5b9a9',
    messagingSenderId: '43511634572',
    projectId: 'smart-fireguard',
    authDomain: 'smart-fireguard.firebaseapp.com',
    storageBucket: 'smart-fireguard.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTiiZB_NJ63NxhGDXbaZbLiOLI3Gh_8Fc',
    appId: '1:43511634572:android:e432f9a50be7f183e5b9a9',
    messagingSenderId: '43511634572',
    projectId: 'smart-fireguard',
    storageBucket: 'smart-fireguard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDITOBebj18cFh803d4jYkOArd0YzDl_lM',
    appId: '1:43511634572:ios:aa8e351166979791e5b9a9',
    messagingSenderId: '43511634572',
    projectId: 'smart-fireguard',
    storageBucket: 'smart-fireguard.firebasestorage.app',
    iosBundleId: 'com.example.smartFireguard',
  );
}
